name: swift
base: core20
version: '5.3.3'
summary: Snap package for the Swift programming language
description: |
  Swift makes it easy to write software that is incredibly fast and safe by design.
  Our goals for Swift are ambitious: we want to make programming simple things easy, and difficult things possible.
grade: devel
confinement: classic
architectures: [amd64]

parts:
  swift-part:
    plugin: dump
    source: https://swift.org/builds/swift-5.3.3-release/ubuntu2004/swift-5.3.3-RELEASE/swift-5.3.3-RELEASE-ubuntu20.04.tar.gz
    build-packages:
        - curl
        - dirmngr
        - gpg
    stage-packages:
        - libcurl4
        - libxml2
        - libedit2
        - libsqlite3-0
        - libc6-dev
        - binutils
        - libgcc-9-dev
        - libstdc++-9-dev
        - libz3-dev
        - zlib1g-dev
        - libpython2.7
        - tzdata
        - git
        - pkg-config
    override-pull: |
        export DEBIAN_FRONTEND=noninteractive
        export GNUPGHOME="$(mktemp -d)"
        curl --progress-bar -fSL "https://swift.org/builds/swift-5.3.3-release/ubuntu2004/swift-5.3.3-RELEASE/swift-5.3.3-RELEASE-ubuntu20.04.tar.gz" -o swift.tar.gz "https://swift.org/builds/swift-5.3.3-release/ubuntu2004/swift-5.3.3-RELEASE/swift-5.3.3-RELEASE-ubuntu20.04.tar.gz.sig" -o swift.tar.gz.sig
        gpg --batch --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-keys "A62AE125BBBFBB96A6E042EC925CC1CCED3D1561"
        gpg --batch --verify swift.tar.gz.sig swift.tar.gz
        tar -xzf swift.tar.gz --strip-components=2
        rm swift.tar.gz.sig
        rm swift.tar.gz
apps:
  swift:
    command: bin/swift
