name: swift
base: core18
version: '5.3.2'
summary: Snap package for the Swift programming language
description: |
  Swift makes it easy to write software that is incredibly fast and safe by design.
  Our goals for Swift are ambitious: we want to make programming simple things easy, and difficult things possible.
grade: devel
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  swift-part:
    source: https://swift.org/builds/swift-5.3.2-release/ubuntu1804/swift-5.3.2-RELEASE/swift-5.3.2-RELEASE-ubuntu18.04.tar.gz
    plugin: nil
    stage-packages:
    - libatomic1
    - libcurl4
    - libxml2
    - libedit2
    - libsqlite3-0
    - libc6-dev
    - binutils
    - libgcc-5-dev
    - libstdc++-5-dev
    - zlib1g-dev
    - libpython2.7
    - tzdata
    - pkg-config

apps:
  swift:
    command: usr/bin/swift