name: swift
base: core18
version: '5.3'
summary: Snap package for the Swift programming language
description: |
  Swift makes it easy to write software that is incredibly fast and safe by design.
  Our goals for Swift are ambitious: we want to make programming simple things easy, and difficult things possible.
grade: devel
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  swift-part:
    plugin: nil
